DFE-Digital/get-into-teaching-api-ruby-client

api-client/Gemfile.lock
I forgot to run `bundle update` in the last version.
=> Udpate get_into_teaching_api_client_faraday dependencies

README.md, api-client/Gemfile.lock, api-client/lib/api/client/version.rb, api-client/lib/api/extensions/get_into_teaching_api_client/caching.rb
We only want the cache to live for a maximum of 10 minutes; this is made up of a 5 minute TTL in the API and 5 minute TTL in this client-side HTTP cache.
=> Drop HTTP cache TTL to 5 minutes

auto-generated-gem/docs/TeachingEventsApi.md, auto-generated-gem/lib/get_into_teaching_api_client/api/teaching_events_api.rb, auto-generated-gem/spec/api/teaching_events_api_spec.rb
I didn't bump the version since this is a very small change and the old version hasn't been referenced anywhere yet.
=> Rename category to type for consistency

README.md, api-client/lib/api/client/version.rb, api-client/lib/api/extensions/get_into_teaching_api_client/caching.rb, api-client/spec/api/extensions/get_into_teaching_api_client/caching_spec.rb
> :warning: **Do not merge down until this has shipped: https://github.com/DFE-Digital/get-into-teaching-api/pull/392**
We were overriding the cache-control header to set a 5m private cache to any API responses deemed 'cacheable' (if they serve an ETag). This was done because it was not possible/straight forward at the time to set cache-control response headers in the API due to the requests being authenticated (and ASP.NET firmly preventing us).
This is no longer the case and we are implementing the cache-control headers in the API, so they can be removed from the API client.
=> Remove cache-control header override

api-client/lib/api/client.rb, api-client/lib/api/extensions/get_into_teaching_api_client/api_client.rb, api-client/lib/api/extensions/get_into_teaching_api_client/caching.rb, api-client/spec/api/extensions/get_into_teaching_api_client/api_client_spec.rb, api-client/spec/api/extensions/get_into_teaching_api_client/caching_spec.rb
- Explicitly format Date/Time attributes in requests
Currently any `DateTime` or `Time` attributes are serialised to JSON by calling `to_s` which, in turn, calls `to_formatted_s(:default)`. The issue with this is that the default formatting behaves differently for `DateTime` or `Time` objects that have a `UTC` offset (as opposed to a `+00:00` offset). It results in `UTC` being present in the formatted date in place of the timezone offset, which isn't supported by the API.
This commit intercepts the serialisation process for both the JSON request body and the query string parameters, explicitly formatting them to ensure the offset is output in the `+/-HH:MM` format.
- Rename Caching extension to ApiClient
This extension used to primarily be about supporting caching, but it now does more …
=> Fix formatting of Date/Time objects during serialization

README.md, api-client/lib/api/client/version.rb
I forgot to bump the ApiClient version when making the previous change to fix date formatting during serialisation.
=> Bump ApiClient version

api-client/Gemfile.lock, api-client/lib/api/extensions/get_into_teaching_api_client/api_client.rb, api-client/spec/api/extensions/get_into_teaching_api_client/api_client_spec.rb
After updating the gem to include the latest API methods for some reason the `Date` types started formatting differently when calling `strftime` with a date/time format -- they changed from including only the date portion:
```
2000-01-24
```
To having the time added onto the end:
```
2000-01-24 00:00:00 +00:00
```
The API rejects this as a valid `Date` value. This commit updates the API client monkey patch to format `Date` objects explicitly.
I had also forgotten to run `bundle install` after updating the API client previously, so this includes the updated `Gemfile.lock`.
=> Format Date correctly in request body/query string

README.md, api-client/lib/api/client/version.rb, api-client/lib/api/extensions/get_into_teaching_api_client/api_client.rb, api-client/spec/api/extensions/get_into_teaching_api_client/api_client_spec.rb
I'm not sure why this has changed - the API used to be happy accepting `DateTime` values such as `2001-01-01 10:00:00 +05:00` but now it expects the format ISO 8601, so `2001-01-01T10:00:00+05:00`.
We're currently getting an error for any TTA sign ups that schedule a phone call due to this being the incorrect format.
=> Update date/time format

api-client/Gemfile.lock, api-client/lib/api/client.rb, api-client/lib/api/client/version.rb, api-client/lib/api/extensions/get_into_teaching_api_client/api_client.rb, api-client/lib/api/models/current.rb, api-client/spec/api/extensions/get_into_teaching_api_client/api_client_spec.rb, api-client/spec/api/models/current_spec.rb
We want to be able to track requests from the app right through to the API. In order to do this we need to set a correlation id in the request headers going to the API. Rails has a request id we can tap into, but getting it into the API client for all requests will be difficult/verbose.
To make life easier this commit updates the API client to expect a request id set on the current thread. We are using
`ActiveSupport::CurrentAttributes` to ensure the thread globals get cleaned up after each request (in Rails).
If a `request_id` is present it will be written to the `Request-Id` header prior to making the API request (ASP.NET Core will pick up on this and use it as the `TraceId`).
We should be able to write to this from our `ApplicationController` in a `before_action` such as:
```
def …
```
=> Support request_id in Thread.current

api-client/lib/api/extensions/get_into_teaching_api_client/api_client.rb, api-client/lib/api/extensions/get_into_teaching_api_client/cache_invalidator.rb, api-client/lib/api/extensions/get_into_teaching_api_client/invalidate_cache.rb, api-client/spec/api/extensions/get_into_teaching_api_client/api_client_spec.rb
Currently, when a teaching event is posted to the API, it will not be immediately available on the hosted environments because of HTTP caching. 
The InvalidateCache middleware checks whether a request is posted to a teaching_event path, and if true, clears the cache.
=> Invalidate cache

README.md, api-client/Gemfile.lock, api-client/lib/api/client/version.rb, api-client/lib/api/extensions/get_into_teaching_api_client/api_client.rb, api-client/lib/api/extensions/get_into_teaching_api_client/cache_invalidator.rb, api-client/spec/api/extensions/get_into_teaching_api_client/api_client_spec.rb
- Bump version
- Make cache invalidation more extensible
Swap the regex of paths for an array of path prefixes and update the tests to be more dynamic, so we don't need to change them when adding additional paths that invalidate the cache.
Update middleware to work correctly when `base_path` is set (we don't use this at the moment, but it will potentially avoid issues in the future).
Minor housekeeping of the api client specs in general.
=> Bump version for cache invalidation

README.md, api-client/lib/api/client/version.rb, auto-generated-gem/docs/TeachingEventsApi.md, auto-generated-gem/lib/get_into_teaching_api_client/api/teaching_events_api.rb, auto-generated-gem/spec/api/teaching_events_api_spec.rb
When SwaggerGen is generating the client library, it is expecting a teaching event to be in a hash with a `body` key for upsert_teaching_event.
SwaggerRequestBody annotation has been added to the API action to match the other post actions, which seems to have fixed this.
=> Remove the need for a `body` key when upserting a teaching event

README.md, api-client/lib/api/client/version.rb, auto-generated-gem/lib/get_into_teaching_api_client/models/classroom_experience_note.rb
Previously it generated a regex that didn't work property; so its been swapped out to check an array of explicit values instead in the API and client-side validation support is removed.
=> Update validation for classroom experience note

README.md, api-client/lib/api/client/version.rb, auto-generated-gem/docs/ClassroomExperienceNote.md, auto-generated-gem/lib/get_into_teaching_api_client/models/classroom_experience_note.rb
This was incorrectly typed as a string in the API - its now been updated.
Swagger-codegen is marking it incorrectly as optional in the docs; its required. I think if I updated the type to be `int?` and then give it a `NotNull` validation criteria it will correct it, but I'll pick that up later.
=> Update school_urn to be an integer

README.md, api-client/lib/api/client/version.rb, auto-generated-gem/docs/TeacherTrainingAdviserSignUp.md, auto-generated-gem/lib/get_into_teaching_api_client/models/teacher_training_adviser_sign_up.rb, auto-generated-gem/spec/models/teacher_training_adviser_sign_up_spec.rb
We require the `adviser_status_id` to be able to identify candidates in a 'closed' state. The API will return this as part of the response for exchanging an access token and expects the app to post the value back.
=> Add adviser_status_id to TeacherTrainingAdviserSignUp

README.md, api-client/lib/api/client/version.rb, auto-generated-gem/docs/ExistingCandidateRequest.md, auto-generated-gem/lib/get_into_teaching_api_client/models/existing_candidate_request.rb, auto-generated-gem/spec/models/existing_candidate_request_spec.rb
We can now optionally add a reference to requests that send an ExistingCandidateRequest. This lets the API tag metrics at
a more granular level.
=> Add reference attribute to existing candidate request

api-client/lib/api/extensions/get_into_teaching_api_client/api_client.rb, api-client/spec/api/extensions/get_into_teaching_api_client/api_client_spec.rb
The API is configured to accept query parameters in the format that the old API client version used (which was based of how Typhoeus did it by default):
```
param=value1,value2
```
Faraday can be configured to use either:
```
param[]=value1,param[]=value2
```
Or:
```
param=value1,param=value2
```
We can probably update the API to support one of the methods Faraday uses (as they are both pretty standard now), but as this needs to be backwards compatible I'm updating the API client to work how it previously did (updating the API to work for multiple scenarios is not straight forward).
I haven't bumped the version as nothing has been shipped with it yet.
=> Correct formatting of array query parameters

auto-generated-gem/docs/TeacherTrainingAdviserApi.md, auto-generated-gem/lib/get_into_teaching_api_client/api/teacher_training_adviser_api.rb, auto-generated-gem/spec/api/teacher_training_adviser_api_spec.rb
The swagger annotation for the return type was missing and so this didn't generate correctly.
=> Fix return type of matchback endpoint

auto-generated-gem/docs/TeacherTrainingAdviserSignUp.md, auto-generated-gem/lib/get_into_teaching_api_client/models/teacher_training_adviser_sign_up.rb, auto-generated-gem/spec/models/teacher_training_adviser_sign_up_spec.rb
Adds an optional parameter to the API: `stage_taught_id`
The [API changes](https://github.com/DFE-Digital/get-into-teaching-api/pull/1326) should be merged prior to this change.
=> Add stage taught to api

auto-generated-gem/docs/TeachingEventAddAttendee.md, auto-generated-gem/lib/get_into_teaching_api_client/models/teaching_event_add_attendee.rb, auto-generated-gem/spec/models/teaching_event_add_attendee_spec.rb
- Adds `Channel_id` attrib to the TeachingEventAddAttendee model 
Link to Trello card: https://trello.com/c/hEzzR5IP/5001-investigate-bam-channel-capture-for-events
=> Adds optional param to TeachingEventAddAttendee
